#!/bin/bash
#
# backup-stuff:
# Backup mySociety CVS repository and other things.
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: backup-stuff,v 1.19 2007-01-06 11:47:37 francis Exp $
#

set -e
PATH=/software/bin:$PATH

RSYNC_RSH=ssh
export RSYNC_RSH
rsyncopts=-raq

if tty 2>&1 > /dev/null ; then
    function debug () {
        echo "backup-cvs:" "$@" 1>&2
    }
    rsyncopts=-rav
else
    function debug () {
        :
    }
fi

# Delete old backups of some databases weekly for privacy
# Delete every database backup older than a year
deleteweekly="fyr"
oneweekback=$( date +%Y%m%dT%H%M%S --date='1 week ago')
oneyearback=$( date +%Y%m%dT%H%M%S --date='1 year ago')
for X in _data_backups_dailydb_????????T??????; do
    # Delete older than a week
    if [[ "$X" < "_data_backups_dailydb_$oneweekback" ]]; then
        #echo "delete weekly: $X"
        chmod u+w $X
        for Y in $deleteweekly
        do
            rm -f $X/$Y.*
        done
        chmod u-w $X
    fi
    # Delete older than a year
    if [[ "$X" < "_data_backups_dailydb_$oneyearback" ]]; then
        echo "delete yearly: $X"
        chmod u+w $X
        rm -fr $X
        chmod u-w $X
    fi
done

# TODO: Maybe delete year / two year old file backups as well

# Get daily copy of backups from server
for thing in /data/backups/dailydb /data/backups/dailyfiles; do
    dir=$( echo $thing | sed s@/@_@g )
    now=$( date +%Y%m%dT%H%M%S )
    target=${dir}_$now

    debug "date of current backup is $now"

    # Find latest backup
    latest=$( ls -d ${dir}_????????T?????? 2> /dev/null | tail -1 )

    if [ x$latest = x$target ] ; then
        debug "last backup has same timestamp; waiting and trying again"
        sleep 1
        exec $0 "$@"
    fi

    trap "echo 'backup of $thing failed' 1>&2 ; rm -rf $target; exit 1" EXIT

    if [ x$latest != x ] ; then
        cp -al $latest $target
    else
        mkdir $target
    fi

    rsync $rsyncopts readbackups@bitter.ukcod.org.uk:$thing/. $target/.

    trap '' EXIT
done

