#!/bin/bash
#
# update-index:
# Create Debian repository index files.
#
# $Id: debian-vhost-update,v 1.5 2008-05-07 14:51:18 keith Exp $
#

if [ "`hostname`" != 'cake' ]
then
    echo "Run on bitter only"
    exit
fi

cd /data/vhost/debian.mysociety.org/docs

for i in `find dists -name "binary-*"`
do
	echo "Generating Packages.gz file for: $i"
	dpkg-scanpackages $i /dev/null | gzip -9c > $i/Packages.gz.new && mv $i/Packages.gz.new $i/Packages.gz || rm $i/Packages.gz.new
done

for i in `find dists -name source`
do
	echo "Generating Sources.gz file for: $i"
	dpkg-scansources $i /dev/null | gzip -9c > $i/Sources.gz.new && mv $i/Sources.gz.new $i/Sources.gz || rm $i/Sources.gz.new
done


