#!/bin/bash
#
# deploy-logger:
# Call to log whenever a deploy action happens.
#
# Arguments are the message to log, as in echo(1).
#
# $Id: deploy-logger,v 1.16 2012-09-26 15:38:55 matthew Exp $
#

HOST=`hostname`
STATE_PATH=/data/state
LOGFILE=deploy-log
PUSH_ATTEMPTS=5
DATELOG=`date +"%Y-%m-%d %X"`
WHO=$SUDO_USER
[ "$WHO" = "" ] && WHO=$USER

if [ "$1" = "-u" ] ; then
    UML=1
    shift
fi

# Create and add to git if we're a new server
if [ ! -e "$STATE_PATH/$HOST" ]
then
    cd $STATE_PATH
    mkdir $HOST
fi
cd $STATE_PATH/$HOST
if [ ! -e "$LOGFILE" ]
then
    touch $LOGFILE
fi

# Add new entry to end of log file
echo "$DATELOG $WHO-" "$@" >>$LOGFILE

# Post notice to IRC about log entry.
# Backgrounded due to ident delay
if [[ ! "$@" =~ "Deployed vhost" || ! "$@" =~ "test.mysociety.org" ]]
then
(( echo nick $HOST; echo user $HOST 8 "*" :mySociety IRCBot; echo notice "#activity" :"$WHO $@"; echo quit; ) | nc irc.mysociety.org 6667 >/dev/null &) 2>/dev/null
fi

# Commit it
if [ x = x$UML ]
then
    git add $LOGFILE
    git commit -q -m "deploy-logger: $@" $LOGFILE

    # Try a few times, as other hosts might be pushing at the same time.
    pushes=0
    while [ $pushes -le $PUSH_ATTEMPTS ]
    do
	(( pushes++ ))
        git push -q origin master 2> /dev/null
	if [ $? == 0 ]
	then
	    break
	fi

	# Pull the changes that have happened since we've been running.
	git pull -q
    done
    if [ $pushes == $PUSH_ATTEMPTS ]
    then
        echo "warning: couldn't git push deploy-logger changes after $pushes attempts"
    fi
fi

exit 0 # otherwise it exits with code of grep

