#!/bin/sh
#
# deploy-logger:
# Call to log whenever a deploy action happens.
#
# Arguments are the message to log, as in echo(1).
#
# $Id: deploy-logger,v 1.5 2006-10-03 09:03:15 francis Exp $
#

HOST=`hostname`
LOGFILE_PATH=/data/servers/state/$HOST/
LOGFILE=deploy-log
DATELOG=`date +"%Y-%m-%d %X"`
WHO=$SUDO_USER
[ "$WHO" = "" ] && WHO=$USER

cd $LOGFILE_PATH
echo "$DATELOG $WHO-" "$@" >>$LOGFILE

cvs -Q commit -m "deploy-logger: $@" $LOGFILE | grep -v "Mailing the commit message to"

exit 0 # otherwise it exits with code of grep

