#!/usr/bin/perl -w
#
# generate-pgpass:
# Creates ~/.pgpass files for users to whom it is convenient to give access to
# databases. Overwrites any existing ~/.pgpass file for the specified users.
#
# Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
# 

my $rcsid = ''; $rcsid .= '$Id: generate-pgpass,v 1.146 2011-01-16 23:30:10 matthew Exp $';

use strict;
require 5.8.0;

use FindBin;
use lib "$FindBin::Bin/../perllib";
use POSIX;

use Data::Dumper;

use mySociety::TempFiles;
use mySociety::ServerClass;

my $servers_dir = "$FindBin::Bin/../../servers";
require "$servers_dir/vhosts.pl";

our ($vhosts, $sites, $databases);

# Permissions above the automatic ones, e.g. for people to have access to live
# databases, or for services that aren't set up as standard.
# XXX these should be moved into flags in vhosts.pl
my %extra_perms = (
    'marmite' => {
        'francis' => ['foi'],
        'louise' => ['foi'],
        'adam' => ['foi'],
        'skenaja' => ['foi'], # so he can do stats and stuff
    },
    'sandwich' => {
        'louise' => ['hm-staging', 'hm', 'foi-testharness'],
    },
    'pudding' => {
    },
    'cake' => {
        'francis' => ['ycml','mapit','dadem','ratty','evel', 'dress'],
        'matthew' => ['ycml','mapit','dadem','ratty','evel', 'bci-emptyhomes', 'dress', 'bbcparlvid'],
        'etienne' => ['bbcparlvid'],
        'louise' => ['news', 'bbcparlvid'],
        'adam' => ['mapit','dadem','ratty','evel'],
        'debbi' => ['ycml'],
        # Sites
        'dademcron' => ['fyr', 'rt'],
    },
    'balti' => {
        'matthew' => ['pb-staging'],
        'louise' => ['hm-testharness'],
        'louise' => ['gut-louise'],
    },
    'peas' => {
        'debbi' => ['fyr'],
        'timsk' => ['pb'],
        'matthew' => ['fyr', 'pb', 'ycml-cllr'],
        'francis' => ['fyr', 'pb'],
    },
    'hotpot' => {
        'fyr' => ['fyr'],
        'guardian' => ['fyr-guardian'],
    },
    'tea' => {
        'guardian' => ['gut', 'fyr-guardian'],
    },
    'bitter' => {
        'matthew' => ['mapit-new', 'bci'],
        'debbi' => ['bci'],
        'francis' => ['bci'],
        'louise' => ['sitestats'],
    },
    'comet' => {
    },
    'fury' => {
    },
    'phoenix' => {
    },
    'rocket' => {
    },
    'samson' => {
    },
    'wildfire' => {
    },
    'majestic' => {
    },
);

# begin with the overrides from above ...
my %perms;
foreach my $host (keys %extra_perms) {
    foreach my $user (keys %{$extra_perms{$host}}) {
        foreach (@{$extra_perms{$host}{$user}}) {
            $perms{$host}{$user}{$_} = 1;
            $perms{$host}{'root'}{$_} = 1;
        }
    }
}

# ... add in logging as the data base user on the same server
foreach (values %$vhosts) {
    next unless $_->{databases};
    my $user = $_->{user} || $sites->{$_->{site}}->{user};
    foreach (@{$_->{databases}}) {
        $perms{$databases->{$_}{host}}{$user}{$_} = 1;
        $perms{$databases->{$_}{host}}{'root'}{$_} = 1;
    }
}

# ... on backup hosts, give root access to all databases
foreach my $database_name (keys %$databases) {
    my $database_info = $databases->{$database_name};
    if ($database_info->{backup}) {
        foreach my $server (mySociety::ServerClass::all_servers_in_class("backups")) {
            $perms{$server}{'root'}{$database_name} = 1;
        }
    }
}

my $server = (uname())[1];
my $database_permissions = $perms{$server};
die "generate-pgpass not configured for server $server" unless $database_permissions;

foreach my $user (sort keys %$database_permissions) {
    my @x = getpwnam($user) or die "$user: getpwnam: $!";
    my ($user_login, $user_pass, $user_uid, $user_gid) = @x;
    my $user_home = $x[7];

    my ($tmpn, $tmph) = mySociety::TempFiles::create_file_to_replace("$user_home/.pgpass") or die "open: $!";
    $tmph->print("# DO NOT EDIT - edit and rerun generate-pgpass instead\n");

    my $databases = $database_permissions->{$user};
    foreach my $database (sort keys %$databases) {
        my $password = `$FindBin::Bin/pgpw $database`;
        chomp $password;
        $tmph->print("*:*:$database:$database:$password\n") || throw Oops("$tmpn: write: $!");
    }
    $tmph->close();

    chmod 0400, $tmpn;
    chown($user_uid, $user_gid, $tmpn);

    my $dest = "$user_home/.pgpass";
    rename($tmpn, $dest);
}

