#!/usr/bin/perl -w

use strict;
my %langs = (
    'cy_GB' => 'cy',
    'de_DE' => 'de',
    'es_ES' => 'es',
    'pt_BR' => 'pt-br',
    'ru_RU' => 'ru',
);

for (<locale/*.*/LC_MESSAGES/PledgeBank.po>) {
    my ($lang) = /locale\/(.*?)\./;
    open(FP, $_) or die $!;
    my $out = '';
    while (<FP>) {
        next unless /^#:.*?pb.js/;
        my $next = <FP>;
        my $fuzzy = 0;
        $fuzzy = 1 if $next =~ /fuzzy/;
        $next = <FP> if $next =~ /^#,/;
        my $msgid = '';
        if ($next eq "msgid \"\"\n") {
            my $l;
            while (($l = <FP>) !~ /msgstr/) {
                chomp($l);
                $msgid .= substr($l, 1, -1);
            }
            $next = $l
        } else {
            ($msgid) = $next =~ /^msgid "(.*)"/;
            $next = <FP>;
        }
        my $msgstr = '';
        if (!$fuzzy) {
            if ($next eq "msgstr \"\"\n") {
                while ((my $l = <FP>) ne "\n") {
                    chomp($l);
                    $msgstr .= substr($l, 1, -1);
                }
            } else {
                ($msgstr) = $next =~ /^msgstr "(.*)"/;
            }
        }
        $out .= "\"$msgid\":\"$msgstr\"\n";
    }
    close FP;
    open (FP, ">pb/web/js/pb.$langs{$lang}.js") or die $!;
    print FP <<EOF;
/*
 * pb.$langs{$lang}.js
 * Translation of JS strings
 *
 * Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
 * Email: matthew AT mysociety.org. WWW: http://www.mysociety.org/
 *
 * \$Id: gettext-makejs,v 1.1 2005-11-13 12:24:24 matthew Exp $
 *
 */

var translation = {
EOF
    print FP $out;
    print FP "}\n";
    close FP;
}
