#!/bin/bash
#
# bin/gettext-makemo
# Convert all .po files of translations into .mo files
#
# --verbose - show status of all translations
#
# Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: gettext-makemo,v 1.10 2007-04-11 14:08:36 francis Exp $

if [ ! -d locale ]
then
    echo "Run in root mysociety directory with locale directory just below"!
    exit
fi

MSGFMT_PARAMS="-v"
if [ "$1" = "--quiet" ]
then
    MSGFMT_PARAMS=""
fi

# count number of times Subject: appears in original, times two
# XXX this needs fixing to do it for each translation domain separately
SUBJECT_COUNT_ORIG=`grep '^"Subject: ' locale/PledgeBank.po locale/PledgeBank.po | egrep -v "^#" | wc --lines`

for X in locale/*.UTF-8
do
    if [ -d $X ]
    then
        cd $X/LC_MESSAGES

        # Convert all .po files to .mo files
        for PO in *.po
        do
            MO=${PO/.po/.mo}
            [ "$1" != "--quiet" ] && echo -n "$X $PO: " 
            msgfmt -c $MSGFMT_PARAMS -o $MO $PO
            SUBJECT_COUNT=`grep '^"Subject: ' $PO  | egrep -v "^#" | wc --lines`
            if [ "$SUBJECT_COUNT" != "$SUBJECT_COUNT_ORIG" ] 
            then
                echo "WARNING: Email 'Subject: ' lines have probably been translated in $X' (got $SUBJECT_COUNT, $SUBJECT_COUNT_ORIG expected)"
            fi
        done

        cd ../../../
    fi
done

