#!/bin/bash
#
# bin/gettext-makemo
# Convert all .po files of translations into .mo files
#
# Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: gettext-makemo,v 1.2 2005-11-28 23:28:21 matthew Exp $

for X in locale/*.*
do
    if [ -d $X ]
    then
        cd $X/LC_MESSAGES
        msgfmt -o PledgeBank.mo PledgeBank.po
        cd -
    fi
done

