#!/bin/bash
#
# bin/gettext-merge
# Update all .po files from new .pot
#
# Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: gettext-merge,v 1.1 2005-11-27 18:00:24 matthew Exp $

for X in locale/*.*
do
    if [ -d $X ]
    then
        cd $X/LC_MESSAGES
        msgmerge --no-wrap -o PledgeBank.poN PledgeBank.po ../../PledgeBank.po
        mv PledgeBank.poN PledgeBank.po
        cd -
    fi
done

