#!/bin/bash
#
# bin/gettext-makemo
# Convert all .po files of translations into .mo files
#
# Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: gettext-makemo,v 1.4 2005-12-05 18:44:18 matthew Exp $

if [ ! -d locale ]
then
    echo "Run in root mysociety directory with locale directory just below"!
    exit
fi

for X in locale/*.UTF-8
do
    if [ -d $X ]
    then
        cd $X/LC_MESSAGES
        echo -n "$X: "
        msgfmt -v -o PledgeBank.mo PledgeBank.po
        cd ../../../
    fi
done

