#!/usr/bin/ruby -w                                                              

unless ARGV.length == 1
  STDERR.puts <<EOUSAGE
Usage: git-post-receive-hook-push-to-mirrors <RESPOSITORY-NAME>

  <RESPOSITORY-NAME> is used to form the github repository URL,
  e.g. 'whatdotheyknow' means the repository URL will be
  'git@GitHub:mysociety/whatdotheyknow.git'.
EOUSAGE
  exit(1)
end

repository = "git@GitHub:mysociety/#{ARGV[0]}.git"
result = 0

STDIN.each do |line|
  rev_old, rev_new, ref = line.chomp.split(" ")

  # If object name of the new commit is all zeros, that indicates that
  # the ref is being deleted.  In that case, the left hand side of the
  # refspec that we push should be empty:

  rev_new = '' if rev_new =~ /^0{40}$/

  refspec = "#{rev_new}:#{ref}"

  puts "Now pushing #{refspec} to the mysociety repository on github (#{repository})"

  unless system("git","push",repository,refspec)
    result = 1
  end
end

exit(result)
