#!/usr/bin/ruby -w                                                              

unless ARGV.length == 1
  STDERR.puts <<EOUSAGE
Usage: git-post-receive-hook-push-to-mirrors <RESPOSITORY-NAME>

  <RESPOSITORY-NAME> is used to form the github repository URL,
  e.g. 'whatdotheyknow' means the repository URL will be
  'git@GitHub:mysociety/whatdotheyknow.git'.
EOUSAGE
  exit(1)
end

repository = "git@GitHub:mysociety/#{ARGV[0]}.git"
result = 0

STDIN.each do |line|
  rev_old, rev_new, ref = line.chomp.split(" ")

  puts "Now pushing #{ref} to the mysociety repository on github (#{repository})"

  unless system("git","push",repository,ref)
    result = 1
  end
end

exit(result)
