#!/bin/bash
#
# localesymlinks:
# Makes symbolic links to names of locale directories which Python's
# gettext requires.
#
# Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: localesymlinks,v 1.1 2005-11-04 10:54:13 francis Exp $
#

cd `dirname $0`

cd ../../mysociety/locale
for X in *.UTF-8
do
    Y=${X/UTF-8/utf}
    if [ ! -e $Y ]
    then
        ln -s $X $Y
    fi
done


