#!/bin/bash
# Shorter interface to deploy scripts on servers.
set -e

function show_help {
	cat <<END
Usage: mysociety COMMAND

COMMAND is any of:
  config - deploy new config for current server
  vhost VHOST - deploy latest version of VHOST, e.g. www.pledgebank.com

Extra parameters are passed through to underlying script.
END
	exit
}

COMMAND=$1
shift
if [ "$COMMAND" = "config" ]
then
	HOST=`hostname`
	/data/mysociety/bin/deploy-configuration /data/servers/$HOST /data/servers/$HOST.pl "$@"
elif [ "$COMMAND" = "vhost" ]
then
    VHOST=$1
    shift
	[ "$VHOST" = "" ] && show_help
	/data/mysociety/bin/deploy-vhost $VHOST "$@"
else
	show_help
fi

