#!/bin/bash
# Shorter interface to deploy scripts on servers.
# Bash script because it uses temporary named pipes <(cmd)

# Obtain hostname
HOST=`hostname`
if [ x$HOST = x ] ; then
    die "can't establish hostname"
fi

# Obtain archetype
cd /data/servers
cvs -Q update serverclass
if [ ! -e /data/servers/serverclass ] ; then
    die "/data/servers/serverclass: No such file or directory"
fi
ARCHETYPES=`echo $HOST | cat - /data/servers/serverclass | \
            sed 's/#.*//' | awk '{
                if (NR == 1) hostname = $1; 
                else if ($1 == hostname) print $2
            }'`
if [ "x$ARCHETYPES" = "x" ] ; then
    die "don't know archetypes for this host ($HOST), add to /data/servers/serverclass"
fi
PRINCIPLE_ARCHETYPE=`echo $ARCHETYPES | sed "s/ /\n/" | tail --lines=1`

# Obtain list of other servers in same principle archetype
SAME_ARCHETYPE=`echo $PRINCIPLE_ARCHETYPE | cat - /data/servers/serverclass | \
    sed 's/#.*//' | awk '{
        if (NR == 1) classname = $1; 
        else if ($2 == classname) print $1
    }'`

# Error reporting
die () {
    echo "mysociety:" "$@" 1>&2
    exit 1
}

show_help () {
	cat <<END
Usage: mysociety COMMAND [OPTIONS]

COMMAND is one of:
    config
        Deploy new config for current server from /data/servers/...
    vhost VHOST
        Deploy latest version of VHOST, e.g. www.pledgebank.com
    test VHOST
        Run test script on VHOST, e.g. testharness.pet.mysociety.org

    dns
        Update the DNS configuration on the current host
    email
        Update the exim virtual mail configuration on the current host

    update
        "cvs update" all of /data/servers and /data/mysociety
    commit
        "cvs commit" all of /data/servers and /data/mysociety
    diff
        "cvs diff -u" all of /data/servers and /data/mysociety

    class COMMAND
        Run a command on all machines in the same principle class as this one

Extra parameters are passed through to underlying deploy-... script.
END
	exit
}

COMMAND=$1
shift || die "specify a command (try --help for help)"

set -e

case $COMMAND in
    config)
        cd /data/servers
        cvs -Q update -dP $HOST.pl
        for ARCHETYPE in $ARCHETYPES
        do
            cvs -Q update -dP $ARCHETYPE
            /data/mysociety/bin/deploy-configuration /data/servers/$ARCHETYPE /data/servers/$HOST.pl "$@"
        done
        cp /data/servers/$HOST.pl "/etc/mysociety/config-settings.pl"
        /data/mysociety/bin/deploy-logger "Deployed configuration for archetypes \"$ARCHETYPES\" with settings \"$HOST.pl\""
        ;;
        
    vhost)
        VHOST=$1
        shift || die "specify a virtual host"
        # deploy vhost
        /data/mysociety/bin/deploy-vhost $VHOST "$@"
        # special code to set up dademcron user and cron job
        if [ "$VHOST" = "services.mysociety.org" -a $( hostname ) = bitter ]; then
            /data/vhost/services.mysociety.org/mysociety/services/DaDem/bin/setup-dademcron
        fi
        ;;

    test) 
        VHOST=$1
        shift || die "specify a virtual host"
        # update code (which also does apachectl graceful, so killing
        # any FastCGI processes holding the database open, so the test script
        # can drop and reload the database)
        /data/mysociety/bin/deploy-vhost $VHOST "$@"
        # launch test script
        VERBOSE=1 /data/mysociety/bin/test-site $VHOST
        ;;

    dns)
        exec /data/mysociety/bin/deploy-dns "$@"
        ;;

    email)
        exec /data/mysociety/bin/deploy-email "$@"
        ;;

    update)
        cd /data/servers
        cvs -Q update -dP
        cd /data/mysociety
        cvs -Q update -dP
        ;;

    commit)
        cd /data/servers
        cvs -Q commit
        cd /data/mysociety
        cvs -Q commit
        ;;

    diff)
        cd /data/servers
        cvs -Q diff -u
        cd /data/mysociety
        cvs -Q diff -u
        ;;

    class)
        for X in $SAME_ARCHETYPE
        do
            echo " -- on $X..."
            ssh $X "$@" || echo " -- ...failed"
        done
        ;;
    *)
	show_help
        ;;
esac

