#!/bin/bash
#
# mysql-schema-compare:
# Compare a schema in a text file with the schema in a live database.
# 
# Parameters are:
# $1 - schema SQL file
# $2 - unix user who can access the live db
# $3 - mysql db name
# $4 - mysql db user
# $5 - mysql db host
# $6 - mysql db port
# You must put any password in ~/.my.cnf (the command line and environment are
# insecure ways to transmit the password)
#
# If the schemas differ, prints a message to standard error and exits with 1.
# If they are the same, quietly exits with code 0.
#
# Copyright (c) 2008 UK Citizens Online Democracy. All rights reserved.
# Email: matthew@mysociety.org; WWW: http://www.mysociety.org/
#

set -e
. /data/mysociety/shlib/deployfns

# Command line parameters
PARAM_SCHEMA=$1
PARAM_UNIX_USER=$2
PARAM_DB_NAME=$3
PARAM_DB_USER=$4
PARAM_DB_HOST=$5
PARAM_DB_PORT=$6

SCHEMATEST=schematest_`hostname`

# XXX use of mktemp here not safe; should make a temporary directory
CVS_SCHEMA_FILE=`mktemp /tmp/ms-deploy-cvsschema.XXXXXX`
CURRENT_SCHEMA_FILE=`mktemp /tmp/ms-deploy-currentschema.XXXXXX`

MYSQLDUMP="/usr/bin/mysqldump --no-data --skip-opt --create-options"

# load schema into temporay db to deal with SET stuff
ssh $PARAM_DB_HOST su root -c \"mysql --port=$PARAM_DB_PORT --execute=\\\"drop database $SCHEMATEST\\\"\" 2>&1 | grep -v "database doesn't exist" || echo -n
ssh $PARAM_DB_HOST su root -c \"mysql --port=$PARAM_DB_PORT --execute=\\\"create database $SCHEMATEST\\\"\" 
cat $PARAM_SCHEMA | ssh $PARAM_DB_HOST su root -c \"mysql --database=$SCHEMATEST --port=$PARAM_DB_PORT\"

ssh $PARAM_DB_HOST su root -c \"$MYSQLDUMP --port $PARAM_DB_PORT $SCHEMATEST \" | grep -v "\-\-databases\|^--\|/\*.*SET\|^\s*$" | sed "s/ ENGINE.*;/;/" | sed "s/,$//;" > $CVS_SCHEMA_FILE

ssh $PARAM_DB_HOST su root -c \"mysql --port=$PARAM_DB_PORT --execute=\\\"drop database $SCHEMATEST\\\"\" 2>&1 | grep -v "database doesn't exist" || echo -n

cat $CVS_SCHEMA_FILE | sort > $CVS_SCHEMA_FILE.sorted

# ... the live database dump
su $PARAM_UNIX_USER --shell "/bin/bash" -c "[ \"${BASH_VERSINFO[0]}\" != \"2\" ] && set -o pipefail; $MYSQLDUMP --user $PARAM_DB_USER --host $PARAM_DB_HOST --port $PARAM_DB_PORT $PARAM_DB_NAME | grep -v \"\-\-databases\|^--\|/\*.*SET\|^\s*$\" | sed \"s/ ENGINE.*;/;/\" | sed \"s/,$//;\"" > $CURRENT_SCHEMA_FILE

cat $CURRENT_SCHEMA_FILE | sort > $CURRENT_SCHEMA_FILE.sorted

if ! diff -w $CURRENT_SCHEMA_FILE.sorted $CVS_SCHEMA_FILE.sorted
then
    warn "Schema in CVS differs from that in MySQL database, you need to update it"
    warn "host: $PARAM_DB_HOST port: $PARAM_DB_PORT database: $PARAM_DB_NAME; user: $PARAM_DB_USER schema: $PARAM_SCHEMA"
    warn "CVS sorted: $CVS_SCHEMA_FILE.sorted; current sorted: $CURRENT_SCHEMA_FILE.sorted"
    warn "CVS schema: $CVS_SCHEMA_FILE; current schema: $CURRENT_SCHEMA_FILE"
    exit 1
fi

rm $CVS_SCHEMA_FILE $CURRENT_SCHEMA_FILE

