#!/bin/bash
#
# psql-schema-compare:
# Compare a schema in a text file with the schema in a live database.
# 
# Parameters are:
# $1 - schema SQL file
# $2 - unix user who can access the live db
# $3 - pgsql db name
# $4 - pgsql db user
# $5 - pgsql db host
# $6 - pgsql db port
# You must put any password in ~/.pgpass (the command line and environment are
# insecure ways to transmit the password)
#
# If the schemas differ, prints a message to standard error and exits with 1.
# If they are the same, quietly exits with code 0.
#
# Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#

set -e
. ../shlib/deployfns

# XXX use of mktemp here not safe; should make a temporary directory
CVS_SCHEMA_FILE=`mktemp /tmp/ms-deploy-cvsschema.XXXXXX`
CURRENT_SCHEMA_FILE=`mktemp /tmp/ms-deploy-currentschema.XXXXXX`
POSTGRES=postgres
SCHEMATEST=schematest_`hostname`

PGDUMP=/usr/lib/postgresql/7.4/bin/pg_dump
if [ "$6" = "5433" ]
then
    PGDUMP=/usr/lib/postgresql/8.1/bin/pg_dump
fi

# load file schema into a temporary place to dump it in the same format as ...
ssh $5 su $POSTGRES -c \""dropdb --port $6 -q $SCHEMATEST"\" 2>&1 | grep -v "does not exist" || echo -n
ssh $5 su $POSTGRES -c \""createdb --port $6 -q $SCHEMATEST"\"
cat $1 | ssh $5 su $POSTGRES -c \""psql --port $6 --file=- -q $SCHEMATEST"\" 2>&1 | grep -v "will create implicit" && echo -n 
ssh $5 su $POSTGRES -c \""$PGDUMP --port $6 --schema-only --schema=public -s $SCHEMATEST"\" | egrep -v "^--|SET SESSION AUTHORIZATION|\\connect - |GRANT ALL|REVOKE ALL|START WITH 1|OWNER TO" | grep -v "SET search_path = public, pg_catalog;" | sed "s/,$//;" | grep -v '^[ \t]*$' > $CVS_SCHEMA_FILE
ssh $5 su $POSTGRES -c \""dropdb --port $6 -q $SCHEMATEST"\"

# ... the live database dump
su $2 -c "$PGDUMP --schema-only --schema=public -U $4 --host $5 --port $6 $3" | egrep -v "^--|SET SESSION AUTHORIZATION|\\connect - |GRANT ALL|REVOKE ALL|START WITH 1|OWNER TO" | grep -v "SET search_path = public, pg_catalog;" | sed "s/,$//;" | grep -v '^[ \t]*$' > $CURRENT_SCHEMA_FILE

# Compare them
if [ "$6" = "5433" ]
then
    # For PostgreSQL 8.1 can just do diff of actual dumps
    if ! diff -u $CURRENT_SCHEMA_FILE $CVS_SCHEMA_FILE
    then
        warn "Schema in CVS differs from that in pgsql 8.1 database, you need to update it"
        warn "host: $5 port: $6 database: $3; user: $4 schema: $1"
        warn "CVS schema: $CVS_SCHEMA_FILE; current schema: $CURRENT_SCHEMA_FILE"
        exit 1
    fi
else
    # Note:  Using sort here is completely evil.  It is because
    # older verions of pg_dump (i.e. PostgreSQL 7.4) don't output the tables in
    # a stable order.  The above code would get confused it a column was moved
    # from one table to another with no other changes.  Hopefully this is
    # unlikely.  More recent pgsql have a fixed pg_dump.  Or a Perl script
    # could be used to compare schemas. If you hate this send us a patch ;)
    # Better actually release a comprehensive schema comparing tool...
    cat $CVS_SCHEMA_FILE | sort > $CVS_SCHEMA_FILE.sorted
    cat $CURRENT_SCHEMA_FILE | sort > $CURRENT_SCHEMA_FILE.sorted

    if ! diff -w $CURRENT_SCHEMA_FILE.sorted $CVS_SCHEMA_FILE.sorted
    then
        warn "Schema in CVS differs from that in pgsql 7.4 database, you need to update it"
        warn "host: $5 port: $6 database: $3; user: $4 schema: $1"
        warn "CVS sorted: $CVS_SCHEMA_FILE.sorted; current sorted: $CURRENT_SCHEMA_FILE.sorted"
        warn "CVS schema: $CVS_SCHEMA_FILE; current schema: $CURRENT_SCHEMA_FILE"
        exit 1
    fi
fi
rm $CVS_SCHEMA_FILE $CURRENT_SCHEMA_FILE


