#!/usr/bin/perl -w -I ../perllib/
#
# rabx:
# Calls RABX functions from command line.  Run with no parameters for help.
#

my $rcsid = ''; $rcsid .= '$Id: rabx,v 1.1 2005-08-09 15:55:41 francis Exp $';

use strict;
use RABX;
use Data::Dumper;
$Data::Dumper::Terse = 1;

if (!scalar(@ARGV)) {
print <<END;
Make a remote function call to a specified RABX service.

    ./rabx URL FUNCTION [PARAMS ...]
    
PARAMS are interpreted as separate scalar parameters to the function.
The return value is displayed in the same format as Perl's Data::Dumper.

Examples:

./rabx http://tea.ukcod.org.uk/gaze Gaze.get_country_from_ip 216.239.37.99
(gets the country code for IP address 216.239.37.99)
END
exit;
}

my $url = shift @ARGV or die "Specify URL as first parameter";
my $function = shift @ARGV or die "Specify function name as second parameter";

my $rabx = new RABX::Client($url) or die "Failed to create RABX client for $url";
my $result = $rabx->call($function, @ARGV);
print Dumper($result);

