#!/bin/sh
#
# make-rails-symlinks
# For Ruby on Rails, run this in exec_extras in vhosts.pl. It makes symlinks
# from vendor to the server version of rails, and migrates the db to the most
# recent version.
#
# Copyright (c) 2007 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: rails-post-deploy,v 1.1 2007-11-27 15:47:34 francis Exp $
#

# $1 should be the directory of the rails app
cd $1

# make sure that there is an app directory, so are in a rails app tree
cd app/..

mkdir -p vendor
cd vendor
for X in actionmailer actionpack actionwebservice activerecord activesupport railties
do
    rm -f $X
    ln -s /usr/share/rails/$X $X
done
rm -f rails
ln -s . rails

cd ..
mkdir -p log
cd log
for X in development.log fastcgi.crash.log production.log test.log
do
    touch $X
done

cd ..
rake db:migrate

