#!/bin/sh
#
# Synchronise NFS servers' files.
#
# Ian Chard <ian@mysociety.org>
#

SYNC_PATH='/export/'

case "$HOSTNAME" in
    'elephant')
        SYNC_PAIR='buffalo'
	;;
    'buffalo')
        SYNC_PAIR='elephant'
	;;
    *)
        echo "$HOSTNAME is not a valid host for this script"
	exit 1
        ;;
esac

# Update the timestamp on a 'flag' file, so we can check that synchronisation is working.
touch $SYNC_PATH/.$HOSTNAME-timestamp

# Run the sync as the last command so the exit status is preserved.
# Errors will still go to stderr despite '-silent'.
/usr/bin/unison -batch -silent -logfile /var/log/unison.log "$SYNC_PATH" "ssh://$SYNC_PAIR//$SYNC_PATH"
