#!/bin/sh
#
# bin/upload_psql
# Uploads psql database remotely.
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: upload_psql,v 1.1 2004-12-07 10:56:47 francis Exp $
#

# This is more of an aide-memoire than a script for now
#pg_dump -U mapit mapit | cwp | ssh -C very.unfortu.net "psql mapit mapit"

